server:
  listen_port: 8000

# add consumption_rate and hash attribute when reading from config
targets:
  - host_name: "server1"
    host_url: "https://127.0.0.1:9001"
    capacity: "30"

  - host_name: server2
    host_url: https://127.0.0.1:9002
    capacity: "30"
  
  - host_name: server3
    host_url: https://127.0.0.1:9003
    capacity: "30"